# Generated by Django 5.2.6 on 2025-09-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_flowershop', '0002_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='admin_flowershop.category', verbose_name='Категория букета'),
        ),
    ]
